DROP TABLE IF EXISTS test.app_user;

CREATE TABLE  test.app_user (
id int(11) NOT NULL AUTO_INCREMENT,
uname char(20) NOT NULL,
pword char(20) NOT NULL,
PRIMARY KEY (id)
);

/*!40000 ALTER TABLE app_user DISABLE KEYS */;

LOCK TABLES app_user WRITE;

INSERT INTO test.app_user VALUES  (37,'sally','somePass'),
(38,'dude','hey2dude');
UNLOCK TABLES;

/*!40000 ALTER TABLE app_user ENABLE KEYS */;

DROP TABLE IF EXISTS test.phone_number;

CREATE TABLE  test.phone_number (
id int(11) NOT NULL AUTO_INCREMENT,
phone varchar(20) NOT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

/*!40000 ALTER TABLE phone_number DISABLE KEYS */;

LOCK TABLES phone_number WRITE;

INSERT INTO test.phone_number VALUES  (1,'(120)345-6789'),
(2,'(208)321-4567'),
(3,'(201)456-0987');


/*!40000 ALTER TABLE phone_number ENABLE KEYS */;

BEGIN
  FOR i IN (SELECT   object_name
            FROM     user_object
            WHERE    object_name IN ('USER_NUMBER')
				AND 	object_type = 'TABLE') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||i.table_name||' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE  test.user_number (
user_id int(11) NOT NULL,
phone_id int(11) NOT NULL,
id int(11) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8;

INSERT INTO test.user_number VALUES  (37,1,1),
(38,3,7),
(38,2,8);

UNLOCK TABLES;

/*!40000 ALTER TABLE user_number ENABLE KEYS */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;